/**
 * Pages Seed Script
 * Seeds the pages collection with all system pages
 *
 * Usage: node scripts/seedPages.js
 */

import { config } from 'dotenv';
config();

import mongoose from 'mongoose';
import Page from '../models/rbac/page.schema.js';

const uri = process.env.MONGO_URI || 'mongodb://localhost:27017';
const dbName = process.env.MONGODB_DATABASE || 'AmasQIS';

// Comprehensive page definitions organized by module category
const pageDefinitions = [
  // ========================================
  // SUPER ADMIN PAGES
  // ========================================
  {
    name: 'super-admin.users',
    displayName: 'Users',
    description: 'User Management',
    route: '/super-admin/users',
    icon: 'ti ti-users',
    moduleCategory: 'super-admin',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'super-admin.roles',
    displayName: 'Roles & Permissions',
    description: 'Role and Permission Management',
    route: '/super-admin/roles-permissions',
    icon: 'ti ti-shield',
    moduleCategory: 'super-admin',
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'super-admin.packages',
    displayName: 'Packages',
    description: 'Subscription Packages Management',
    route: '/super-admin/packages',
    icon: 'ti ti-package',
    moduleCategory: 'super-admin',
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'super-admin.subscriptions',
    displayName: 'Subscriptions',
    description: 'Company Subscriptions',
    route: '/super-admin/subscriptions',
    icon: 'ti ti-id',
    moduleCategory: 'super-admin',
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'super-admin.companies',
    displayName: 'Companies',
    description: 'Company Management',
    route: '/super-admin/companies',
    icon: 'ti ti-building',
    moduleCategory: 'super-admin',
    sortOrder: 50,
    isSystem: true,
  },

  // ========================================
  // HRM PAGES
  // ========================================
  {
    name: 'hrm.dashboard',
    displayName: 'HR Dashboard',
    description: 'Human Resources Dashboard',
    route: '/hrm/dashboard',
    icon: 'ti ti-dashboard',
    moduleCategory: 'hrm',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'hrm.employees',
    displayName: 'Employees',
    description: 'Employee Management',
    route: '/hrm/employees',
    icon: 'ti ti-users',
    moduleCategory: 'hrm',
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'hrm.department',
    displayName: 'Department',
    description: 'Department Management',
    route: '/hrm/department',
    icon: 'ti ti-building-arch',
    moduleCategory: 'hrm',
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'hrm.designation',
    displayName: 'Designation',
    description: 'Designation/Job Titles',
    route: '/hrm/designation',
    icon: 'ti ti-badge',
    moduleCategory: 'hrm',
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'hrm.policies',
    displayName: 'Policies',
    description: 'Company Policies',
    route: '/hrm/policies',
    icon: 'ti ti-file-description',
    moduleCategory: 'hrm',
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'hrm.tickets',
    displayName: 'Tickets List',
    description: 'Help Desk Tickets',
    route: '/hrm/tickets',
    icon: 'ti ti-ticket',
    moduleCategory: 'hrm',
    sortOrder: 60,
    isSystem: true,
  },
  {
    name: 'hrm.tickets-detail',
    displayName: 'Tickets Detail',
    description: 'Ticket Details',
    route: '/hrm/tickets-detail',
    icon: 'ti ti-ticket',
    moduleCategory: 'hrm',
    sortOrder: 70,
    isSystem: true,
  },
  {
    name: 'hrm.holidays',
    displayName: 'Holidays',
    description: 'Holiday Management',
    route: '/hrm/holidays',
    icon: 'ti ti-calendar-event',
    moduleCategory: 'hrm',
    sortOrder: 80,
    isSystem: true,
  },
  {
    name: 'hrm.leaves-admin',
    displayName: 'Leaves (Admin)',
    description: 'Leave Management - Admin View',
    route: '/hrm/leaves-admin',
    icon: 'ti ti-calendar-off',
    moduleCategory: 'hrm',
    sortOrder: 90,
    isSystem: true,
  },
  {
    name: 'hrm.leaves-employee',
    displayName: 'Leaves (Employee)',
    description: 'Leave Management - Employee View',
    route: '/hrm/leaves-employee',
    icon: 'ti ti-calendar-off',
    moduleCategory: 'hrm',
    sortOrder: 100,
    isSystem: true,
  },
  {
    name: 'hrm.leave-settings',
    displayName: 'Leave Settings',
    description: 'Leave Configuration',
    route: '/hrm/leave-settings',
    icon: 'ti ti-settings',
    moduleCategory: 'hrm',
    sortOrder: 110,
    isSystem: true,
  },
  {
    name: 'hrm.attendance-admin',
    displayName: 'Attendance (Admin)',
    description: 'Attendance Management - Admin View',
    route: '/hrm/attendance-admin',
    icon: 'ti ti-calendar-check',
    moduleCategory: 'hrm',
    sortOrder: 120,
    isSystem: true,
  },
  {
    name: 'hrm.attendance-employee',
    displayName: 'Attendance (Employee)',
    description: 'Attendance Management - Employee View',
    route: '/hrm/attendance-employee',
    icon: 'ti ti-calendar-check',
    moduleCategory: 'hrm',
    sortOrder: 130,
    isSystem: true,
  },
  {
    name: 'hrm.timesheet',
    displayName: 'Timesheet',
    description: 'Timesheet Management',
    route: '/hrm/timesheet',
    icon: 'ti ti-clock',
    moduleCategory: 'hrm',
    sortOrder: 140,
    isSystem: true,
  },
  {
    name: 'hrm.shift-schedule',
    displayName: 'Shift & Schedule',
    description: 'Shift Scheduling',
    route: '/hrm/shift-schedule',
    icon: 'ti ti-calendar-time',
    moduleCategory: 'hrm',
    sortOrder: 150,
    isSystem: true,
  },
  {
    name: 'hrm.shift-management',
    displayName: 'Shift Management',
    description: 'Shift Configuration',
    route: '/hrm/shift-management',
    icon: 'ti ti-clock-hour-4',
    moduleCategory: 'hrm',
    sortOrder: 160,
    isSystem: true,
  },
  {
    name: 'hrm.shift-batches',
    displayName: 'Shift Batches',
    description: 'Shift Batch Management',
    route: '/hrm/shift-batches',
    icon: 'ti ti-stack',
    moduleCategory: 'hrm',
    sortOrder: 170,
    isSystem: true,
  },
  {
    name: 'hrm.overtime',
    displayName: 'Overtime',
    description: 'Overtime Management',
    route: '/hrm/overtime',
    icon: 'ti ti-clock-hour-12',
    moduleCategory: 'hrm',
    sortOrder: 180,
    isSystem: true,
  },
  {
    name: 'hrm.performance-indicator',
    displayName: 'Performance Indicator',
    description: 'Performance Indicators',
    route: '/hrm/performance-indicator',
    icon: 'ti ti-chart-bar',
    moduleCategory: 'hrm',
    sortOrder: 190,
    isSystem: true,
  },
  {
    name: 'hrm.performance-review',
    displayName: 'Performance Review',
    description: 'Performance Reviews',
    route: '/hrm/performance-review',
    icon: 'ti ti-star',
    moduleCategory: 'hrm',
    sortOrder: 200,
    isSystem: true,
  },
  {
    name: 'hrm.performance-appraisal',
    displayName: 'Performance Appraisal',
    description: 'Performance Appraisals',
    route: '/hrm/performance-appraisal',
    icon: 'ti me-1 ti-trophy',
    moduleCategory: 'hrm',
    sortOrder: 210,
    isSystem: true,
  },
  {
    name: 'hrm.goal-tracking',
    displayName: 'Goal Tracking',
    description: 'Goal Tracking',
    route: '/hrm/goal-tracking',
    icon: 'ti ti-target',
    moduleCategory: 'hrm',
    sortOrder: 220,
    isSystem: true,
  },
  {
    name: 'hrm.goal-type',
    displayName: 'Goal Type',
    description: 'Goal Types',
    route: '/hrm/goal-type',
    icon: 'ti ti-flag',
    moduleCategory: 'hrm',
    sortOrder: 230,
    isSystem: true,
  },
  {
    name: 'hrm.training',
    displayName: 'Training List',
    description: 'Training Programs',
    route: '/hrm/training',
    icon: 'ti ti-graduation-cap',
    moduleCategory: 'hrm',
    sortOrder: 240,
    isSystem: true,
  },
  {
    name: 'hrm.trainers',
    displayName: 'Trainers',
    description: 'Trainer Management',
    route: '/hrm/trainers',
    icon: 'ti ti-user-star',
    moduleCategory: 'hrm',
    sortOrder: 250,
    isSystem: true,
  },
  {
    name: 'hrm.training-type',
    displayName: 'Training Type',
    description: 'Training Types',
    route: '/hrm/training-type',
    icon: 'ti ti-tag',
    moduleCategory: 'hrm',
    sortOrder: 260,
    isSystem: true,
  },
  {
    name: 'hrm.promotions',
    displayName: 'Promotions',
    description: 'Employee Promotions',
    route: '/hrm/promotions',
    icon: 'ti ti-arrow-up',
    moduleCategory: 'hrm',
    sortOrder: 270,
    isSystem: true,
  },
  {
    name: 'hrm.resignation',
    displayName: 'Resignation',
    description: 'Resignation Management',
    route: '/hrm/resignation',
    icon: 'ti ti-logout',
    moduleCategory: 'hrm',
    sortOrder: 280,
    isSystem: true,
  },
  {
    name: 'hrm.termination',
    displayName: 'Termination',
    description: 'Termination Management',
    route: '/hrm/termination',
    icon: 'ti ti-user-x',
    moduleCategory: 'hrm',
    sortOrder: 290,
    isSystem: true,
  },
  {
    name: 'hrm.provident-fund',
    displayName: 'Provident Fund',
    description: 'Provident Fund Management',
    route: '/hrm/provident-fund',
    icon: 'ti ti-pig-money',
    moduleCategory: 'hrm',
    sortOrder: 300,
    isSystem: true,
  },
  {
    name: 'hrm.employee-salary',
    displayName: 'Employee Salary',
    description: 'Salary Management',
    route: '/hrm/employee-salary',
    icon: 'ti me-1 ti-cash',
    moduleCategory: 'hrm',
    sortOrder: 310,
    isSystem: true,
  },
  {
    name: 'hrm.payslip',
    displayName: 'Payslip',
    description: 'Payslip Management',
    route: '/hrm/payslip',
    icon: 'ti ti-file-invoice',
    moduleCategory: 'hrm',
    sortOrder: 320,
    isSystem: true,
  },
  {
    name: 'hrm.payroll-items',
    displayName: 'Payroll Items',
    description: 'Payroll Configuration',
    route: '/hrm/payroll-items',
    icon: 'ti ti-list-details',
    moduleCategory: 'hrm',
    sortOrder: 330,
    isSystem: true,
  },

  // ========================================
  // PROJECTS PAGES
  // ========================================
  {
    name: 'projects.dashboard',
    displayName: 'Projects Dashboard',
    description: 'Projects Dashboard',
    route: '/projects/dashboard',
    icon: 'ti ti-dashboard',
    moduleCategory: 'projects',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'projects.clients',
    displayName: 'Clients',
    description: 'Client Management',
    route: '/projects/clients',
    icon: 'ti ti-users',
    moduleCategory: 'projects',
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'projects.projects',
    displayName: 'Projects',
    description: 'Project Management',
    route: '/projects/projects',
    icon: 'ti ti-folder',
    moduleCategory: 'projects',
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'projects.tasks',
    displayName: 'Tasks',
    description: 'Task Management',
    route: '/projects/tasks',
    icon: 'ti ti-checkbox',
    moduleCategory: 'projects',
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'projects.task-board',
    displayName: 'Task Board',
    description: 'Kanban Task Board',
    route: '/projects/task-board',
    icon: 'ti ti-kanban',
    moduleCategory: 'projects',
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'projects.jobs',
    displayName: 'Jobs',
    description: 'Job Management',
    route: '/projects/jobs',
    icon: 'ti ti-briefcase',
    moduleCategory: 'projects',
    sortOrder: 60,
    isSystem: true,
  },
  {
    name: 'projects.candidates',
    displayName: 'Candidates',
    description: 'Candidate Management',
    route: '/projects/candidates',
    icon: 'ti ti-user-check',
    moduleCategory: 'projects',
    sortOrder: 70,
    isSystem: true,
  },
  {
    name: 'projects.referrals',
    displayName: 'Referrals',
    description: 'Job Referrals',
    route: '/projects/referrals',
    icon: 'ti ti-share',
    moduleCategory: 'projects',
    sortOrder: 80,
    isSystem: true,
  },

  // ========================================
  // CRM PAGES
  // ========================================
  {
    name: 'crm.dashboard',
    displayName: 'Deals Dashboard',
    description: 'Deals Dashboard',
    route: '/crm/deals-dashboard',
    icon: 'ti ti-dashboard',
    moduleCategory: 'crm',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'crm.leads-dashboard',
    displayName: 'Leads Dashboard',
    description: 'Leads Dashboard',
    route: '/crm/leads-dashboard',
    icon: 'ti ti-dashboard',
    moduleCategory: 'crm',
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'crm.companies',
    displayName: 'Companies',
    description: 'Company Management',
    route: '/crm/companies',
    icon: 'ti ti-building',
    moduleCategory: 'crm',
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'crm.deals',
    displayName: 'Deals',
    description: 'Deal Management',
    route: '/crm/deals',
    icon: 'ti ti-handshake',
    moduleCategory: 'crm',
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'crm.leads',
    displayName: 'Leads',
    description: 'Lead Management',
    route: '/crm/leads',
    icon: 'ti ti-user-plus',
    moduleCategory: 'crm',
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'crm.pipeline',
    displayName: 'Pipeline',
    description: 'Sales Pipeline',
    route: '/crm/pipeline',
    icon: 'ti ti-git-branch',
    moduleCategory: 'crm',
    sortOrder: 60,
    isSystem: true,
  },
  {
    name: 'crm.analytics',
    displayName: 'Analytics',
    description: 'CRM Analytics',
    route: '/crm/analytics',
    icon: 'ti me-1 ti-chart-pie',
    moduleCategory: 'crm',
    sortOrder: 70,
    isSystem: true,
  },
  {
    name: 'crm.activities',
    displayName: 'Activities',
    description: 'CRM Activities',
    route: '/crm/activities',
    icon: 'ti ti-activity',
    moduleCategory: 'crm',
    sortOrder: 80,
    isSystem: true,
  },

  // ========================================
  // FINANCE PAGES
  // ========================================
  {
    name: 'finance.estimates',
    displayName: 'Estimates',
    description: 'Estimate Management',
    route: '/finance/estimates',
    icon: 'ti ti-file-invoice',
    moduleCategory: 'finance',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'finance.invoices',
    displayName: 'Invoices',
    description: 'Invoice Management',
    route: '/finance/invoices',
    icon: 'ti me-1 ti-receipt',
    moduleCategory: 'finance',
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'finance.payments',
    displayName: 'Payments',
    description: 'Payment Management',
    route: '/finance/payments',
    icon: 'ti ti-credit-card',
    moduleCategory: 'finance',
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'finance.expenses',
    displayName: 'Expenses',
    description: 'Expense Management',
    route: '/finance/expenses',
    icon: 'ti ti-receipt-2',
    moduleCategory: 'finance',
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'finance.taxes',
    displayName: 'Taxes',
    description: 'Tax Management',
    route: '/finance/taxes',
    icon: 'ti ti-percentage',
    moduleCategory: 'finance',
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'finance.categories',
    displayName: 'Categories',
    description: 'Expense Categories',
    route: '/finance/categories',
    icon: 'ti ti-category',
    moduleCategory: 'finance',
    sortOrder: 60,
    isSystem: true,
  },
  {
    name: 'finance.budgets',
    displayName: 'Budgets',
    description: 'Budget Management',
    route: '/finance/budgets',
    icon: 'ti ti-chart-donut',
    moduleCategory: 'finance',
    sortOrder: 70,
    isSystem: true,
  },
  {
    name: 'finance.budget-expenses',
    displayName: 'Budget Expenses',
    description: 'Budget Expenses',
    route: '/finance/budget-expenses',
    icon: 'ti me-1 ti-chart-donut-2',
    moduleCategory: 'finance',
    sortOrder: 80,
    isSystem: true,
  },
  {
    name: 'finance.budget-revenues',
    displayName: 'Budget Revenues',
    description: 'Budget Revenues',
    route: '/finance/budget-revenues',
    icon: 'ti ti-chart-donut-3',
    moduleCategory: 'finance',
    sortOrder: 90,
    isSystem: true,
  },

  // ========================================
  // REPORTS PAGES
  // ========================================
  {
    name: 'reports.expense-report',
    displayName: 'Expense Report',
    description: 'Expense Reports',
    route: '/reports/expense-report',
    icon: 'ti ti-file-analytics',
    moduleCategory: 'reports',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'reports.invoice-report',
    displayName: 'Invoice Report',
    description: 'Invoice Reports',
    route: '/reports/invoice-report',
    icon: 'ti ti-file-invoice',
    moduleCategory: 'reports',
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'reports.payment-report',
    displayName: 'Payment Report',
    description: 'Payment Reports',
    route: '/reports/payment-report',
    icon: 'ti ti-credit-card',
    moduleCategory: 'reports',
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'reports.project-report',
    displayName: 'Project Report',
    description: 'Project Reports',
    route: '/reports/project-report',
    icon: 'ti ti-folder',
    moduleCategory: 'reports',
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'reports.task-report',
    displayName: 'Task Report',
    description: 'Task Reports',
    route: '/reports/task-report',
    icon: 'ti ti-checkbox',
    moduleCategory: 'reports',
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'reports.user-report',
    displayName: 'User Report',
    description: 'User Reports',
    route: '/reports/user-report',
    icon: 'ti ti-users',
    moduleCategory: 'reports',
    sortOrder: 60,
    isSystem: true,
  },
  {
    name: 'reports.employee-report',
    displayName: 'Employee Report',
    description: 'Employee Reports',
    route: '/reports/employee-report',
    icon: 'ti ti-user',
    moduleCategory: 'reports',
    sortOrder: 70,
    isSystem: true,
  },
  {
    name: 'reports.payslip-report',
    displayName: 'Payslip Report',
    description: 'Payslip Reports',
    route: '/reports/payslip-report',
    icon: 'ti me-1 ti-file-invoice',
    moduleCategory: 'reports',
    sortOrder: 80,
    isSystem: true,
  },
  {
    name: 'reports.attendance-report',
    displayName: 'Attendance Report',
    description: 'Attendance Reports',
    route: '/reports/attendance-report',
    icon: 'ti ti-calendar-check',
    moduleCategory: 'reports',
    sortOrder: 90,
    isSystem: true,
  },
  {
    name: 'reports.leave-report',
    displayName: 'Leave Report',
    description: 'Leave Reports',
    route: '/reports/leave-report',
    icon: 'ti ti-calendar-off',
    moduleCategory: 'reports',
    sortOrder: 100,
    isSystem: true,
  },
  {
    name: 'reports.daily-report',
    displayName: 'Daily Report',
    description: 'Daily Reports',
    route: '/reports/daily-report',
    icon: 'ti ti-calendar',
    moduleCategory: 'reports',
    sortOrder: 110,
    isSystem: true,
  },

  // ========================================
  // APPLICATIONS PAGES
  // ========================================
  {
    name: 'apps.chat',
    displayName: 'Chat',
    description: 'Chat Application',
    route: '/applications/chat',
    icon: 'ti ti-messages',
    moduleCategory: 'applications',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'apps.voice-call',
    displayName: 'Voice Call',
    description: 'Voice Calling',
    route: '/applications/voice-call',
    icon: 'ti ti-phone-call',
    moduleCategory: 'applications',
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'apps.video-call',
    displayName: 'Video Call',
    description: 'Video Calling',
    route: '/applications/video-call',
    icon: 'ti ti-video',
    moduleCategory: 'applications',
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'apps.outgoing-call',
    displayName: 'Outgoing Call',
    description: 'Outgoing Calls',
    route: '/applications/outgoing-call',
    icon: 'ti ti-phone-outgoing',
    moduleCategory: 'applications',
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'apps.incoming-call',
    displayName: 'Incoming Call',
    description: 'Incoming Calls',
    route: '/applications/incoming-call',
    icon: 'ti ti-phone-incoming',
    moduleCategory: 'applications',
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'apps.call-history',
    displayName: 'Call History',
    description: 'Call History',
    route: '/applications/call-history',
    icon: 'ti ti-history',
    moduleCategory: 'applications',
    sortOrder: 60,
    isSystem: true,
  },
  {
    name: 'apps.calendar',
    displayName: 'Calendar',
    description: 'Calendar Application',
    route: '/applications/calendar',
    icon: 'ti ti-calendar',
    moduleCategory: 'applications',
    sortOrder: 70,
    isSystem: true,
  },
  {
    name: 'apps.email',
    displayName: 'Email',
    description: 'Email Application',
    route: '/applications/email',
    icon: 'ti ti-mail',
    moduleCategory: 'applications',
    sortOrder: 80,
    isSystem: true,
  },
  {
    name: 'apps.todo',
    displayName: 'To Do',
    description: 'Todo List',
    route: '/applications/todo',
    icon: 'ti ti-checklist',
    moduleCategory: 'applications',
    sortOrder: 90,
    isSystem: true,
  },
  {
    name: 'apps.notes',
    displayName: 'Notes',
    description: 'Notes Application',
    route: '/applications/notes',
    icon: 'ti ti-note',
    moduleCategory: 'applications',
    sortOrder: 100,
    isSystem: true,
  },
  {
    name: 'apps.social-feed',
    displayName: 'Social Feed',
    description: 'Social Feed',
    route: '/applications/social-feed',
    icon: 'ti ti-message-circle',
    moduleCategory: 'applications',
    sortOrder: 110,
    isSystem: true,
  },
  {
    name: 'apps.file-manager',
    displayName: 'File Manager',
    description: 'File Management',
    route: '/applications/file-manager',
    icon: 'ti ti-folder',
    moduleCategory: 'applications',
    sortOrder: 120,
    isSystem: true,
  },
  {
    name: 'apps.kanban',
    displayName: 'Kanban',
    description: 'Kanban Board',
    route: '/applications/kanban',
    icon: 'ti ti-kanban',
    moduleCategory: 'applications',
    sortOrder: 130,
    isSystem: true,
  },

  // ========================================
  // ADMINISTRATION PAGES
  // ========================================
  {
    name: 'admin.general-settings',
    displayName: 'General Settings',
    description: 'General Application Settings',
    route: '/admin/settings/general',
    icon: 'ti ti-settings',
    moduleCategory: 'administration',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'admin.website-settings',
    displayName: 'Website Settings',
    description: 'Website Configuration',
    route: '/admin/settings/website',
    icon: 'ti ti-world',
    moduleCategory: 'administration',
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'admin.app-settings',
    displayName: 'App Settings',
    description: 'Application Configuration',
    route: '/admin/settings/app',
    icon: 'ti ti-device-mobile',
    moduleCategory: 'administration',
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'admin.system-settings',
    displayName: 'System Settings',
    description: 'System Configuration',
    route: '/admin/settings/system',
    icon: 'ti ti-settings-automation',
    moduleCategory: 'administration',
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'admin.financial-settings',
    displayName: 'Financial Settings',
    description: 'Financial Configuration',
    route: '/admin/settings/financial',
    icon: 'ti ti-currency',
    moduleCategory: 'administration',
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'admin.other-settings',
    displayName: 'Other Settings',
    description: 'Other Configuration',
    route: '/admin/settings/other',
    icon: 'ti ti-settings-2',
    moduleCategory: 'administration',
    sortOrder: 60,
    isSystem: true,
  },

  // ========================================
  // CONTENT PAGES
  // ========================================
  {
    name: 'content.blogs',
    displayName: 'Blogs',
    description: 'Blog Management',
    route: '/content/blogs',
    icon: 'ti ti-article',
    moduleCategory: 'content',
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'content.blog-categories',
    displayName: 'Blog Categories',
    description: 'Blog Categories',
    route: '/content/blog-categories',
    icon: 'ti ti-category',
    moduleCategory: 'content',
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'content.blog-comments',
    displayName: 'Blog Comments',
    description: 'Blog Comments',
    route: '/content/blog-comments',
    icon: 'ti ti-message',
    moduleCategory: 'content',
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'content.blog-tags',
    displayName: 'Blog Tags',
    description: 'Blog Tags',
    route: '/content/blog-tags',
    icon: 'ti ti-tag',
    moduleCategory: 'content',
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'content.countries',
    displayName: 'Countries',
    description: 'Country Management',
    route: '/content/countries',
    icon: 'ti ti-world',
    moduleCategory: 'content',
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'content.states',
    displayName: 'States',
    description: 'State/Province Management',
    route: '/content/states',
    icon: 'ti ti-map',
    moduleCategory: 'content',
    sortOrder: 60,
    isSystem: true,
  },
  {
    name: 'content.cities',
    displayName: 'Cities',
    description: 'City Management',
    route: '/content/cities',
    icon: 'ti ti-building-arch',
    moduleCategory: 'content',
    sortOrder: 70,
    isSystem: true,
  },
  {
    name: 'content.testimonials',
    displayName: 'Testimonials',
    description: 'Testimonial Management',
    route: '/content/testimonials',
    icon: 'ti ti-quote',
    moduleCategory: 'content',
    sortOrder: 80,
    isSystem: true,
  },
  {
    name: 'content.faq',
    displayName: "FAQ's",
    description: 'Frequently Asked Questions',
    route: '/content/faq',
    icon: 'ti me-1 ti-help',
    moduleCategory: 'content',
    sortOrder: 90,
    isSystem: true,
  },
  {
    name: 'content.contacts',
    displayName: 'Contacts',
    description: 'Contact Management',
    route: '/content/contacts',
    icon: 'ti ti-address-book',
    moduleCategory: 'content',
    sortOrder: 100,
    isSystem: true,
  },

  // ========================================
  // ASSETS & KNOWLEDGE BASE
  // ========================================
  {
    name: 'assets.assets',
    displayName: 'Assets',
    description: 'Asset Management',
    route: '/assets/assets',
    icon: 'ti ti-box',
    moduleCategory: null,
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'assets.categories',
    displayName: 'Asset Categories',
    description: 'Asset Categories',
    route: '/assets/categories',
    icon: 'ti ti-category',
    moduleCategory: null,
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'knowledge.base',
    displayName: 'Knowledge Base',
    description: 'Knowledge Base',
    route: '/knowledge/base',
    icon: 'ti ti-book',
    moduleCategory: null,
    sortOrder: 30,
    isSystem: true,
  },

  // ========================================
  // USER PAGES
  // ========================================
  {
    name: 'user.profile',
    displayName: 'Profile',
    description: 'User Profile',
    route: '/user/profile',
    icon: 'ti ti-user',
    moduleCategory: null,
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'user.gallery',
    displayName: 'Gallery',
    description: 'User Gallery',
    route: '/user/gallery',
    icon: 'ti ti-photo',
    moduleCategory: null,
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'user.timeline',
    displayName: 'Timeline',
    description: 'User Timeline',
    route: '/user/timeline',
    icon: 'ti me-1 ti-clock-hour-10',
    moduleCategory: null,
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'user.search',
    displayName: 'Search Results',
    description: 'Search Results',
    route: '/user/search',
    icon: 'ti ti-search',
    moduleCategory: null,
    sortOrder: 40,
    isSystem: true,
  },

  // ========================================
  // AUTHENTICATION PAGES
  // ========================================
  {
    name: 'auth.login',
    displayName: 'Login',
    description: 'User Login',
    route: '/login',
    icon: 'ti ti-login',
    moduleCategory: null,
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'auth.register',
    displayName: 'Register',
    description: 'User Registration',
    route: '/register',
    icon: 'ti ti-user-plus',
    moduleCategory: null,
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'auth.forgot-password',
    displayName: 'Forgot Password',
    description: 'Forgot Password',
    route: '/forgot-password',
    icon: 'ti ti-lock',
    moduleCategory: null,
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'auth.reset-password',
    displayName: 'Reset Password',
    description: 'Reset Password',
    route: '/reset-password',
    icon: 'ti ti-key',
    moduleCategory: null,
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'auth.email-verification',
    displayName: 'Email Verification',
    description: 'Email Verification',
    route: '/email-verification',
    icon: 'ti ti-mail',
    moduleCategory: null,
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'auth.two-step',
    displayName: '2 Step Verification',
    description: 'Two-Factor Authentication',
    route: '/two-step-verification',
    icon: 'ti ti-lock-code',
    moduleCategory: null,
    sortOrder: 60,
    isSystem: true,
  },
  {
    name: 'auth.lock-screen',
    displayName: 'Lock Screen',
    description: 'Lock Screen',
    route: '/lock-screen',
    icon: 'ti ti-lock',
    moduleCategory: null,
    sortOrder: 70,
    isSystem: true,
  },

  // ========================================
  // ERROR & MAINTENANCE PAGES
  // ========================================
  {
    name: 'error.404',
    displayName: '404 Error',
    description: 'Page Not Found',
    route: '/error-404',
    icon: 'ti me-1 ti-error-404',
    moduleCategory: null,
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'error.500',
    displayName: '500 Error',
    description: 'Server Error',
    route: '/error-500',
    icon: 'ti ti-alert-triangle',
    moduleCategory: null,
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'pages.coming-soon',
    displayName: 'Coming Soon',
    description: 'Coming Soon Page',
    route: '/coming-soon',
    icon: 'ti ti-clock',
    moduleCategory: null,
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'pages.under-maintenance',
    displayName: 'Under Maintenance',
    description: 'Maintenance Page',
    route: '/maintenance',
    icon: 'ti ti-tools',
    moduleCategory: null,
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'pages.under-construction',
    displayName: 'Under Construction',
    description: 'Construction Page',
    route: '/construction',
    icon: 'ti ti-hammer',
    moduleCategory: null,
    sortOrder: 50,
    isSystem: true,
  },

  // ========================================
  // LEGAL & POLICY PAGES
  // ========================================
  {
    name: 'legal.api-keys',
    displayName: 'API Keys',
    description: 'API Key Management',
    route: '/legal/api-keys',
    icon: 'ti ti-api',
    moduleCategory: null,
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'legal.privacy-policy',
    displayName: 'Privacy Policy',
    description: 'Privacy Policy',
    route: '/privacy-policy',
    icon: 'ti ti-shield-lock',
    moduleCategory: null,
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'legal.terms',
    displayName: "Terms & Conditions",
    description: 'Terms and Conditions',
    route: '/terms',
    icon: 'ti ti-file-text',
    moduleCategory: null,
    sortOrder: 30,
    isSystem: true,
  },

  // ========================================
  // PRICING & DOCUMENTATION
  // ========================================
  {
    name: 'pages.pricing',
    displayName: 'Pricing',
    description: 'Pricing Page',
    route: '/pricing',
    icon: 'ti ti-tag',
    moduleCategory: null,
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'pages.documentation',
    displayName: 'Documentation',
    description: 'Documentation',
    route: '/documentation',
    icon: 'ti ti-book',
    moduleCategory: null,
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'pages.change-log',
    displayName: 'Change Log',
    description: 'Version Change Log',
    route: '/changelog',
    icon: 'ti me-1 ti-git-commit',
    moduleCategory: null,
    sortOrder: 30,
    isSystem: true,
  },

  // ========================================
  // DASHBOARDS
  // ========================================
  {
    name: 'dashboard.admin',
    displayName: 'Admin Dashboard',
    description: 'Admin Dashboard',
    route: '/admin/dashboard',
    icon: 'ti ti-dashboard',
    moduleCategory: null,
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'dashboard.employee',
    displayName: 'Employee Dashboard',
    description: 'Employee Dashboard',
    route: '/employee/dashboard',
    icon: 'ti ti-dashboard',
    moduleCategory: null,
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'dashboard.starter',
    displayName: 'Starter',
    description: 'Starter Page',
    route: '/starter',
    icon: 'ti me-1 ti-rocket',
    moduleCategory: null,
    sortOrder: 30,
    isSystem: true,
  },

  // ========================================
  // UI COMPONENTS (Base UI, Advanced UI, etc.)
  // ========================================
  {
    name: 'ui.base-ui',
    displayName: 'Base UI',
    description: 'Base UI Components',
    route: '/ui/base-ui',
    icon: 'ti ti-shape',
    moduleCategory: null,
    sortOrder: 10,
    isSystem: true,
  },
  {
    name: 'ui.advanced-ui',
    displayName: 'Advanced UI',
    description: 'Advanced UI Components',
    route: '/ui/advanced-ui',
    icon: 'ti ti-flame',
    moduleCategory: null,
    sortOrder: 20,
    isSystem: true,
  },
  {
    name: 'ui.charts',
    displayName: 'Charts',
    description: 'Chart Components',
    route: '/ui/charts',
    icon: 'ti ti-chart-bar',
    moduleCategory: null,
    sortOrder: 30,
    isSystem: true,
  },
  {
    name: 'ui.icons',
    displayName: 'Icons',
    description: 'Icon Library',
    route: '/ui/icons',
    icon: 'ti ti-icons',
    moduleCategory: null,
    sortOrder: 40,
    isSystem: true,
  },
  {
    name: 'ui.forms',
    displayName: 'Forms',
    description: 'Form Components',
    route: '/ui/forms',
    icon: 'ti ti-forms',
    moduleCategory: null,
    sortOrder: 50,
    isSystem: true,
  },
  {
    name: 'ui.tables',
    displayName: 'Tables',
    description: 'Table Components',
    route: '/ui/tables',
    icon: 'ti ti-table',
    moduleCategory: null,
    sortOrder: 60,
    isSystem: true,
  },
  {
    name: 'ui.maps',
    displayName: 'Maps',
    description: 'Map Components',
    route: '/ui/maps',
    icon: 'ti ti-map',
    moduleCategory: null,
    sortOrder: 70,
    isSystem: true,
  },
];

const stats = {
  created: 0,
  updated: 0,
  skipped: 0,
  errors: [],
};

async function seedPages() {
  try {
    console.log('🔌 Connecting to MongoDB...');
    console.log(`   Database: ${dbName}`);
    await mongoose.connect(uri, { dbName });
    console.log('✅ Connected!\n');

    console.log('📦 Starting Pages Seed...\n');
    console.log('='.repeat(70));

    for (const pageDef of pageDefinitions) {
      try {
        // Check if page already exists
        let page = await Page.findOne({ name: pageDef.name });

        if (page) {
          // Update existing page (preserve some fields if needed)
          Object.assign(page, {
            displayName: pageDef.displayName,
            description: pageDef.description,
            route: pageDef.route,
            icon: pageDef.icon,
            moduleCategory: pageDef.moduleCategory,
            sortOrder: pageDef.sortOrder,
            isSystem: pageDef.isSystem,
            updatedAt: new Date(),
          });
          await page.save();
          stats.updated++;
          console.log(`✏️  Updated: ${pageDef.displayName} (${pageDef.name})`);
        } else {
          // Create new page
          page = new Page(pageDef);
          await page.save();
          stats.created++;
          console.log(`✅ Created: ${pageDef.displayName} (${pageDef.name})`);
        }
      } catch (error) {
        console.error(`❌ Error processing ${pageDef.name}: ${error.message}`);
        stats.errors.push({ page: pageDef.name, error: error.message });
      }
    }

    console.log('\n' + '='.repeat(70));
    console.log('📊 SEED SUMMARY');
    console.log('='.repeat(70));
    console.log(`✅ Created: ${stats.created}`);
    console.log(`✏️  Updated: ${stats.updated}`);
    console.log(`⏭️  Skipped: ${stats.skipped}`);
    console.log(`❌ Errors: ${stats.errors.length}`);

    if (stats.errors.length > 0) {
      console.log('\n❌ Error Details:');
      stats.errors.forEach(err => {
        console.log(`   - ${err.page}: ${err.error}`);
      });
    }

    // Verify pages
    console.log('\n📋 Pages in Database (grouped by category):');
    const groupedPages = await Page.getGroupedByModule();
    groupedPages.forEach(group => {
      const category = group._id || 'Other';
      console.log(`\n   ${category.toUpperCase()} (${group.count} pages):`);
      group.pages.slice(0, 5).forEach(page => {
        console.log(`      ✅ ${page.displayName} (${page.name})`);
      });
      if (group.pages.length > 5) {
        console.log(`      ... and ${group.pages.length - 5} more`);
      }
    });

    console.log('\n✅ Pages seed complete!');

    await mongoose.disconnect();

  } catch (error) {
    console.error('\n❌ Seed Error:', error.message);
    console.error(error.stack);
    await mongoose.disconnect();
    process.exit(1);
  }
}

seedPages();
